### ISSUE TITLE
The output of the test name in selenoid-ui is limited.

### ISSUE THREAD

**Issue by DegtyarevAlexandr** [aerokube/selenoid-ui#136] opened 2018-12-29 10:24 UTC
In Selenoid, you can set your own test name (container with browser)
The documentation is this paragraph ([3.1.5.The name of the user test: the name](https://aerokube.com/selenoid/latest/#_custom_test_name_name) )
Currently 51 characters fit in the title.

![_151](https://user-images.githubusercontent.com/38922846/50537104-e782e700-0b6c-11e9-8a5d-d2bc5edb9c20.jpg)

But some names exceed this threshold.

It would be great if it would be possible to display long names in several lines or in a running line or in another way, in which the entire name will be visible.

**Comment by lanwen** [comment] 2019-03-10 12:24
It should be scrollable, isn't it?

**Comment by DegtyarevAlexandr** [comment] 2019-03-11 07:33
> It should be scrollable, isn't it?
Now it is not.

--------------------------------------------
At the moment we can see the full name in the tooltip, if we hover the cursor over the name.
![Выделение_002](https://user-images.githubusercontent.com/38922846/54107019-00b7d780-43e9-11e9-9f53-d9751cd716ef.jpg)

Or we can go inside the container (by clicking on the name)
![Выделение_003](https://user-images.githubusercontent.com/38922846/54107047-1927f200-43e9-11e9-9ae4-6e345c9cb3b4.jpg)

**Comment by savinov** [comment] 2019-04-22 12:58
This limitation is caused by CSS in ui/src/components/Sessions/style.scss
```
    .session-cap {
    ...
      &__name {
        overflow: hidden;
```

Please consider more space for test names instead of hiding overflowed text. I think something about 200 characters is enough.

**Comment by vania-pooh** [comment] 2019-04-22 13:13
@savinov PRs are welcome. :)

**Comment by lanwen** [comment] 2019-04-23 08:48
this limitation was introduced to not brake the view on multiple sessions on small screens 

actually I want to change that into something like this
![image](https://user-images.githubusercontent.com/1964214/56567463-47d2e400-65b5-11e9-8975-0937a9ed25ab.png)

**Comment by savinov** [comment] 2019-04-23 09:01
Looks nice.
Maybe breaking long lines into parts would suitable for this UI too, so test-name might be as long as user wants.

**Comment by lanwen** [comment] 2019-12-01 22:58
Hey, @savinov can you try latest https://github.com/aerokube/selenoid-ui/releases/tag/1.9.1 release? It should address the long test name issue

**Comment by lanwen** [comment] 2020-07-29 08:54
closing as it should be fine now

**Closed by lanwen** 2020-07-29 08:54 UTC
Labels: improvement
