### ISSUE TITLE
Display the name of the cucumber or allure step directly on top of the screen

### ISSUE THREAD

**Issue by devmaster-st** [aerokube/selenoid-ui#411] opened 2021-02-10 08:28 UTC
There is a proposal to display text over the screen. It would be possible to display the name of the cucumber or allure step directly on top of the screen, so that it would be better to understand which step has now been performed or what condition is expected.

**Comment by vania-pooh** [comment] 2021-02-10 14:47
@devmaster-st do you mean on video screen?

**Comment by devmaster-st** [comment] 2021-02-10 14:55
Yes. Да

ср, 10 февр. 2021 г., 17:47 Ivan Krutov <notifications@github.com>:

**Comment by vania-pooh** [comment] 2021-02-11 14:40
Duplicate of aerokube/selenoid#685.

**Closed** 2021-02-11 14:40 UTC
